package oathkeeperrules

import (
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
	"text/template"

	"github.com/Masterminds/sprig/v3"
	intrav1 "github.com/echovisionlab/geul-event-contracts/gen/api/intra/v1"
	managev1 "github.com/echovisionlab/geul-event-contracts/gen/api/manage/v1"
	openv1 "github.com/echovisionlab/geul-event-contracts/gen/api/open/v1"
	policyv1 "github.com/echovisionlab/geul-event-contracts/gen/api/policy/v1"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/reflect/protoregistry"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	"sigs.k8s.io/yaml"
)

func mustRepoRoot(t *testing.T) string {
	t.Helper()
	workingDirectory, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd() error = %v", err)
	}
	root, err := FindRepoRoot(workingDirectory)
	if err != nil {
		t.Fatalf("FindRepoRoot() error = %v", err)
	}
	return root
}

func repositoryRouteConfig(t *testing.T) routeConfig {
	t.Helper()
	root := mustRepoRoot(t)
	routes, err := loadRouteConfig(root)
	if err != nil {
		t.Fatalf("loadRouteConfig() error = %v", err)
	}
	return routes
}

func TestGenerateRulesKeepsStaticRoutingAndHeader(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	for _, want := range [][]byte{
		[]byte("# Code generated by cmd/generate-oathkeeper-rules. DO NOT EDIT."),
		[]byte("version: v26.2.0"),
		[]byte(`url: 'http://api.example.invalid:8000'`),
		[]byte(`url: 'http://collab.example.invalid:3003'`),
		[]byte("'__AUTH_HEADER_NAME__':"),
		[]byte("'__INTERNAL_SERVICE_HEADER_NAME__':"),
		[]byte("- id: manage-admin"),
	} {
		if !bytes.Contains(rules, want) {
			t.Fatalf("generated rules do not contain %q", want)
		}
	}
}

func TestGeneratedRulesUseConfiguredExactOrigins(t *testing.T) {
	routes := repositoryRouteConfig(t)
	routes.Origins.API = "https://www.example.invalid:8443"
	routes.Origins.Auth = "https://www.example.invalid:8443"
	routes.Origins.Collab = "https://www.example.invalid:8443"
	routes.Upstreams.API = "http://backend.internal:8000"
	routes.Upstreams.Collab = "http://collab.internal:3003"

	rules, err := generateRules(routes)
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	for _, forbidden := range [][]byte{
		[]byte(`<https?://[^/]+`),
		[]byte(`[^/]*collab[^/]*`),
		[]byte(`auth.example.invalid`),
		[]byte(`collab.example.invalid`),
	} {
		if bytes.Contains(rules, forbidden) {
			t.Fatalf("generated rules contain forbidden generic or stale host pattern %q", forbidden)
		}
	}

	for _, tc := range []struct {
		id     string
		origin string
		path   string
	}{
		{id: "api-health", origin: `https://www\.example\.invalid:8443`, path: `/health`},
		{id: "api-ses-callback", origin: `https://www\.example\.invalid:8443`, path: `/callbacks/ses`},
		{id: "mcp", origin: `https://www\.example\.invalid:8443`, path: `/mcp`},
		{id: "manage-admin", origin: `https://www\.example\.invalid:8443/api/rpc`, path: `/api\.manage`},
		{id: "open-api", origin: `https://www\.example\.invalid:8443/api/rpc`, path: `/api\.open`},
		{id: "upload-endpoint", origin: `https://www\.example\.invalid:8443`, path: `/api/upload/`},
		{id: "auth-login", origin: `https://www\.example\.invalid:8443`, path: `/api/auth/login`},
		{id: "auth-self-service-read", origin: `https://www\.example\.invalid:8443`, path: `/api/auth/self-service/`},
		{id: "auth-webauthn-runtime", origin: `https://www\.example\.invalid:8443`, path: `/api/auth/\.well-known/ory/webauthn`},
		{id: "collab-websocket", origin: `https://www\.example\.invalid:8443`, path: `/collab/(?P<type>`},
	} {
		block := ruleBlock(t, rules, tc.id)
		if !bytes.Contains(block, []byte(tc.origin)) || !bytes.Contains(block, []byte(tc.path)) {
			t.Errorf("rule %s does not own exact configured origin/path:\n%s", tc.id, block)
		}
	}
}

func TestManageRulesGroupEveryExactRPCByRole(t *testing.T) {
	routes := repositoryRouteConfig(t)
	rules, err := generateRules(routes)
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}
	roles, err := collectManageAuthorizationRoles()
	if err != nil {
		t.Fatalf("collectManageAuthorizationRoles() error = %v", err)
	}

	roleOrder := []policyv1.AuthorizationRole{
		policyv1.AuthorizationRole_ADMIN,
		policyv1.AuthorizationRole_AUTHOR,
		policyv1.AuthorizationRole_USER,
	}
	if got := bytes.Count(rules, []byte("- id: manage-")); got != len(roleOrder) {
		t.Fatalf("generated Manage rules = %d, want one for each of %d roles", got, len(roleOrder))
	}

	matchers := make(map[policyv1.AuthorizationRole]*regexp.Regexp, len(roleOrder))
	for _, role := range roleOrder {
		block := ruleBlock(t, rules, "manage-"+roleID(role))
		if bytes.Contains(block, []byte(`api\.manage\.v1\..*`)) {
			t.Fatalf("%s Manage rule contains a package wildcard:\n%s", role, block)
		}
		matchers[role] = ruleURLRegexp(t, block)
	}

	for expectedRole, services := range roles {
		for service, methods := range services {
			for _, method := range methods {
				for _, origin := range []string{routes.Origins.API, routes.Origins.APIInternal} {
					requestURL := fmt.Sprintf("%s/api/rpc/api.manage.v1.%s/%s", origin, service, method)
					var matchedRoles []policyv1.AuthorizationRole
					for _, candidateRole := range roleOrder {
						if matchers[candidateRole].MatchString(requestURL) {
							matchedRoles = append(matchedRoles, candidateRole)
						}
					}
					if len(matchedRoles) != 1 || matchedRoles[0] != expectedRole {
						t.Errorf("%s matched roles %v, want exactly %s", requestURL, matchedRoles, expectedRole)
					}
				}
			}
		}
	}

	unknownURL := routes.Origins.API + "/api/rpc/api.manage.v1.UnknownService/UnknownProcedure"
	for role, matcher := range matchers {
		if matcher.MatchString(unknownURL) {
			t.Errorf("unknown Manage procedure matched %s", role)
		}
	}
}

func TestSESEventCallbackRuleIsAnonymousExactAndCredentialScrubbed(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	block := ruleBlock(t, rules, "api-ses-callback")
	for _, want := range [][]byte{
		[]byte(`url: '<https://site\.example\.invalid/callbacks/ses>'`),
		[]byte("      - POST\n"),
		[]byte("    - handler: anonymous\n"),
		[]byte("    - handler: header\n"),
		[]byte("    url: 'http://api.example.invalid:8000'\n"),
	} {
		if !bytes.Contains(block, want) {
			t.Errorf("SES callback rule is missing %q:\n%s", want, block)
		}
	}
	for _, forbidden := range [][]byte{
		[]byte("handler: cookie_session"),
		[]byte("handler: bearer_token"),
		[]byte("handler: noop"),
		[]byte("/callbacks/.*"),
	} {
		if bytes.Contains(block, forbidden) {
			t.Errorf("SES callback rule contains forbidden authority or broad matcher %q:\n%s", forbidden, block)
		}
	}
}

func TestAuthRulesAreAnonymousNoopAndCannotMatchProductAPIs(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	for _, id := range []string{
		"auth-preflight",
		"auth-login",
		"auth-login-flows",
		"auth-self-service-read",
		"auth-self-service-submit",
		"auth-sessions",
		"auth-schemas",
		"auth-health",
		"auth-webauthn-runtime",
	} {
		block := ruleBlock(t, rules, id)
		for _, want := range [][]byte{
			[]byte("    - handler: anonymous\n"),
			[]byte("    - handler: noop\n"),
			[]byte("    url: 'http://api.example.invalid:8000'\n"),
		} {
			if !bytes.Contains(block, want) {
				t.Errorf("auth rule %s is missing %q:\n%s", id, want, block)
			}
		}
		for _, forbidden := range [][]byte{
			[]byte("handler: cookie_session"),
			[]byte("handler: bearer_token"),
			[]byte("handler: header"),
			[]byte("api\\.manage"),
			[]byte("api\\.open"),
			[]byte("api\\.intra"),
			[]byte("/upload/"),
			[]byte("/hooks/"),
		} {
			if bytes.Contains(block, forbidden) {
				t.Errorf("auth rule %s contains forbidden authority or product route %q:\n%s", id, forbidden, block)
			}
		}
	}

	apiHealth := ruleBlock(t, rules, "api-health")
	if !bytes.Contains(apiHealth, []byte(`url: '<https://site\.example\.invalid/health>'`)) {
		t.Errorf("API health rule is not exact:\n%s", apiHealth)
	}
	if !bytes.Contains(apiHealth, []byte("    - handler: header\n")) {
		t.Errorf("API health does not scrub caller credentials:\n%s", apiHealth)
	}
	for _, forbidden := range [][]byte{[]byte("/health(?:"), []byte("/health/.*")} {
		if bytes.Contains(apiHealth, forbidden) {
			t.Errorf("API health rule contains path-family alias %q:\n%s", forbidden, apiHealth)
		}
	}

	for id, want := range map[string]string{
		"auth-login":               `url: '<https://site\.example\.invalid/api/auth/login>'`,
		"auth-login-flows":         `url: '<https://site\.example\.invalid/api/auth/login/flows>'`,
		"auth-self-service-read":   `url: '<https://site\.example\.invalid/api/auth/self-service/(?:(?:verification|settings)/(?:browser|flows)|logout(?:/browser)?|errors|methods/oidc/callback/[^/]+)>'`,
		"auth-self-service-submit": `url: '<https://site\.example\.invalid/api/auth/self-service/(?:verification|settings)>'`,
	} {
		block := ruleBlock(t, rules, id)
		if !bytes.Contains(block, []byte(want)) {
			t.Errorf("auth rule %s does not use its exact hard-cut matcher:\n%s", id, block)
		}
		if bytes.Contains(block, []byte("/?")) {
			t.Errorf("auth rule %s retains a trailing-slash alias:\n%s", id, block)
		}
	}
	for _, forbidden := range [][]byte{
		[]byte(`url: '<https://site\.example\.invalid/auth`),
		[]byte(`url: '<https://site\.example\.invalid/verification`),
	} {
		if bytes.Contains(rules, forbidden) {
			t.Errorf("generated rules retain removed user-facing route alias %q", forbidden)
		}
	}

	preflight := ruleBlock(t, rules, "auth-preflight")
	wantMatcher := `url: '<https://site\.example\.invalid/api/auth(?:/login(?:/flows)?|/self-service/(?:(?:verification|settings)(?:/(?:browser|flows))?|logout(?:/browser)?|errors|methods/oidc/callback/[^/]+)|/sessions/.*|/schemas/.*|/health/.*|/\.well-known/ory/webauthn\.js)>'`
	if !bytes.Contains(preflight, []byte(wantMatcher)) {
		t.Errorf("auth preflight is not bounded to the non-preflight route families:\n%s", preflight)
	}
	for _, forbidden := range []string{"/self-service/.*", "recovery", "/api\\.", "/upload/", "/hooks/"} {
		if bytes.Contains(preflight, []byte(forbidden)) {
			t.Errorf("auth preflight contains broader forbidden matcher %q:\n%s", forbidden, preflight)
		}
	}
	for _, blockID := range []string{"auth-preflight", "auth-self-service-read", "auth-self-service-submit"} {
		matcher := ruleURLRegexp(t, ruleBlock(t, rules, blockID))
		for _, rawPath := range []string{
			"/self-service/login/browser",
			"/self-service/login/flows",
			"/self-service/login",
			"/self-service/registration/browser",
			"/self-service/registration/flows",
			"/self-service/registration",
		} {
			if matcher.MatchString("https://site.example.invalid" + rawPath) {
				t.Errorf("auth rule %s publicly exposes retired raw browser controller %q", blockID, rawPath)
			}
		}
	}
}

func TestPublicApplicationRoutesScrubCredentials(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	for _, id := range []string{"api-health", "api-ses-callback", "api-rpc-preflight", "upload-preflight"} {
		block := ruleBlock(t, rules, id)
		if !bytes.Contains(block, []byte("    - handler: header\n")) {
			t.Errorf("public application route %s does not use the credential-scrubbing mutator:\n%s", id, block)
		}
	}
	for _, id := range []string{
		"auth-preflight",
		"auth-login",
		"auth-login-flows",
		"auth-self-service-read",
		"auth-self-service-submit",
		"auth-sessions",
		"auth-schemas",
		"auth-health",
		"auth-webauthn-runtime",
	} {
		block := ruleBlock(t, rules, id)
		if !bytes.Contains(block, []byte("    - handler: noop\n")) {
			t.Errorf("auth facade route %s does not preserve the Kratos credential boundary:\n%s", id, block)
		}
	}
}

func TestBrowserAuthenticatedRulesOverwriteCanonicalSessionHeaderOnly(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}
	for _, id := range []string{"manage-admin", "manage-auth", "collab-websocket", "upload-endpoint"} {
		block := ruleBlock(t, rules, id)
		if !bytes.Contains(block, []byte("    - handler: header\n")) {
			t.Errorf("authenticated rule %s does not use the trusted header mutator:\n%s", id, block)
		}
		if bytes.Contains(block, []byte("handler: bearer_token")) {
			t.Errorf("authenticated rule %s retains unsupported bearer authentication", id)
		}
	}
	if got := bytes.Count(rules, []byte("handler: bearer_token")); got != 0 {
		t.Fatalf("generated bearer authenticator uses = %d, want none", got)
	}
	if got := bytes.Count(rules, []byte("handler: oauth2_introspection")); got != 1 {
		t.Fatalf("generated OAuth introspection authenticator uses = %d, want the exact MCP rule only", got)
	}

	root := mustRepoRoot(t)
	configuration, err := os.ReadFile(filepath.Join(root, "config/oathkeeper/oathkeeper.yml"))
	if err != nil {
		t.Fatalf("read Oathkeeper config: %v", err)
	}
	for _, header := range []string{
		"X-Session-Id:",
		"Cookie: ''",
		"Authorization: ''",
	} {
		if !bytes.Contains(configuration, []byte(header)) {
			t.Errorf("Oathkeeper header mutator is missing %q", header)
		}
	}
	if !bytes.Contains(configuration, []byte(`'__INTERNAL_SERVICE_HEADER_NAME__': '{{ env "TOKEN_SIGNING_SECRET" }}'`)) {
		t.Fatal("Oathkeeper remote_json is missing the configurable gateway internal-service header")
	}
	if !bytes.Contains(configuration, []byte("    trust_forwarded_headers: true\n")) {
		t.Fatal("Oathkeeper does not trust the deployment proxy's overwritten public scheme header")
	}
	for _, forbidden := range []string{
		`env "INTERNAL_SERVICE_SECRET"`,
		"IDENTITY_INTERNAL_SERVICE_SECRET",
		"GATEWAY_ASSERTION_SECRET",
	} {
		if bytes.Contains(configuration, []byte(forbidden)) {
			t.Errorf("Oathkeeper gateway assertion retains identity-secret compatibility %q", forbidden)
		}
	}

	compose, err := os.ReadFile(filepath.Join(root, "compose/identity.yml"))
	if err != nil {
		t.Fatalf("read identity compose: %v", err)
	}
	const mapping = "TOKEN_SIGNING_SECRET: ${BACKEND_TOKEN_SIGNING_SECRET:?set BACKEND_TOKEN_SIGNING_SECRET for trusted backend calls}"
	if bytes.Count(compose, []byte(mapping)) != 2 {
		t.Fatalf("identity compose canonical token-secret mappings = %d, want Kratos and Oathkeeper", bytes.Count(compose, []byte(mapping)))
	}
	for _, forbidden := range []string{
		"LEGACY_BACKEND_INTERNAL_SERVICE_SECRET",
		"LEGACY_IDENTITY_INTERNAL_SERVICE_SECRET",
		"LEGACY_GATEWAY_ASSERTION_SECRET",
		"IDENTITY_INTERNAL_SERVICE_SECRET:",
		"GATEWAY_ASSERTION_SECRET:",
		`{"X-Internal-Service":`,
	} {
		if bytes.Contains(compose, []byte(forbidden)) {
			t.Errorf("identity compose allows secret cross-use through %q", forbidden)
		}
	}
}

func TestPublicPathNamespacesAndStripPaths(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}
	for _, tc := range []struct {
		id     string
		path   string
		strip  string
		forbid string
	}{
		{id: "auth-login", path: "/api/auth/login", strip: "strip_path: /api/auth", forbid: `url: '<https://site\.example\.invalid/login>'`},
		{id: "manage-admin", path: "/api/rpc", strip: "strip_path: /api/rpc", forbid: `url: '<https://site\.example\.invalid/api\.manage`},
		{id: "collab-websocket", path: "/collab/(?P<type>", strip: "strip_path: /collab", forbid: "auth.example.invalid"},
		{id: "upload-endpoint", path: "/api/upload/", strip: "strip_path: /api", forbid: `url: '<https://site\.example\.invalid/upload/.*>'`},
	} {
		block := ruleBlock(t, rules, tc.id)
		if !bytes.Contains(block, []byte(tc.path)) || !bytes.Contains(block, []byte(tc.strip)) {
			t.Errorf("rule %s does not use the required public path namespace and strip path:\n%s", tc.id, block)
		}
		if tc.forbid != "" && bytes.Contains(block, []byte(tc.forbid)) {
			t.Errorf("rule %s retains an unnamespaced route %q:\n%s", tc.id, tc.forbid, block)
		}
	}
	for _, raw := range []string{"https://site.example.invalid/login", "https://site.example.invalid/self-service/", "https://site.example.invalid/sessions/"} {
		if bytes.Contains(rules, []byte(raw)) {
			t.Errorf("generated rules expose raw Kratos browser path %q", raw)
		}
	}
}

func TestCollaborationMatchersRequireExactLocaleRoomPath(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	for _, id := range []string{"collab-websocket", "collab-websocket-admin"} {
		block := ruleBlock(t, rules, id)
		if !bytes.Contains(block, []byte(`/(?P<id>[^/]+)/(?P<locale>[^/]+)>`)) {
			t.Errorf("rule %s does not require the exact locale room suffix:\n%s", id, block)
		}
		if bytes.Contains(block, []byte(`/(?P<id>[^/]+)>`)) {
			t.Errorf("rule %s still admits the legacy locale-less room path:\n%s", id, block)
		}
	}
}

func TestMenuCollaborationUsesAdminMatcher(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	admin := ruleBlock(t, rules, "collab-websocket-admin")
	if !bytes.Contains(admin, []byte(`(?P<type>page|menu|campaign`)) {
		t.Errorf("Admin collaboration rule does not admit Menu rooms:\n%s", admin)
	}
	standard := ruleBlock(t, rules, "collab-websocket")
	if bytes.Contains(standard, []byte(`|menu`)) {
		t.Errorf("Standard collaboration rule unexpectedly admits Admin-only Menu rooms:\n%s", standard)
	}
}

func TestInternalAPIOriginIsLimitedToRPCMatchers(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	internalOrigin := []byte(`http://oathkeeper\.example\.invalid:4455/api/rpc`)
	for _, id := range []string{"block-internal-api", "manage-admin", "open-api"} {
		if block := ruleBlock(t, rules, id); !bytes.Contains(block, internalOrigin) {
			t.Errorf("rule %s does not admit the configured internal RPC origin:\n%s", id, block)
		}
	}
	for _, id := range []string{"api-health", "api-rpc-preflight", "upload-preflight", "upload-endpoint", "auth-login", "collab-websocket"} {
		if block := ruleBlock(t, rules, id); bytes.Contains(block, internalOrigin) {
			t.Errorf("rule %s unexpectedly admits the internal RPC origin:\n%s", id, block)
		}
	}
}

type gatewayTemplateSession struct {
	Subject string
	Extra   map[string]any
}

func executeGatewayTemplate(t *testing.T, source string, session gatewayTemplateSession) (string, error) {
	t.Helper()
	tmpl, err := template.New("gateway").
		Option("missingkey=zero").
		Funcs(template.FuncMap{
			"print": func(value any) string {
				if value == nil {
					return ""
				}
				return fmt.Sprintf("%v", value)
			},
		}).
		Funcs(sprig.TxtFuncMap()).
		Parse(source)
	if err != nil {
		return "", err
	}
	var output bytes.Buffer
	err = tmpl.Execute(&output, session)
	return output.String(), err
}

func oathkeeperHeaderTemplates(t *testing.T) map[string]string {
	t.Helper()
	root := mustRepoRoot(t)
	raw, err := os.ReadFile(filepath.Join(root, "config/oathkeeper/oathkeeper.yml"))
	if err != nil {
		t.Fatalf("read Oathkeeper config: %v", err)
	}
	var config map[string]any
	if err := yaml.Unmarshal(raw, &config); err != nil {
		t.Fatalf("decode Oathkeeper config: %v", err)
	}
	mutators := config["mutators"].(map[string]any)
	header := mutators["header"].(map[string]any)
	headerConfig := header["config"].(map[string]any)
	rawHeaders := headerConfig["headers"].(map[string]any)
	headers := make(map[string]string, len(rawHeaders))
	for name, value := range rawHeaders {
		headers[name] = value.(string)
	}
	return headers
}

func TestSessionGatewayTemplateFailsClosed(t *testing.T) {
	headers := oathkeeperHeaderTemplates(t)
	accountIdentityID := "018f5e2a-7c31-7a43-8b7c-56e20c34a992"
	sessionID := "018f5e2a-7c31-7a43-8b7c-56e20c34a993"
	valid := gatewayTemplateSession{
		Subject: accountIdentityID,
		Extra: map[string]any{
			"id": sessionID,
		},
	}

	if len(headers) != 3 {
		t.Fatalf("Oathkeeper header count = %d, want session plus two credential scrubs", len(headers))
	}
	for _, scrubbed := range []string{
		"Cookie",
		"Authorization",
	} {
		if value, ok := headers[scrubbed]; !ok || value != "" {
			t.Fatalf("Oathkeeper scrub header %s = %q, present = %v", scrubbed, value, ok)
		}
	}
	gotSession, err := executeGatewayTemplate(t, headers["X-Session-Id"], valid)
	if err != nil || gotSession != sessionID {
		t.Fatalf("session header = %q, error = %v", gotSession, err)
	}
	gotSubject, err := executeGatewayTemplate(t, memberSubjectTemplate, valid)
	if err != nil || gotSubject != accountIdentityID {
		t.Fatalf("SpiceDB subject = %q, error = %v", gotSubject, err)
	}

	for _, tc := range []struct {
		name    string
		session gatewayTemplateSession
	}{
		{name: "missing subject", session: gatewayTemplateSession{}},
		{name: "malformed subject", session: gatewayTemplateSession{Subject: "not-an-account-identity"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			if value, err := executeGatewayTemplate(t, memberSubjectTemplate, tc.session); err == nil {
				t.Fatalf("SpiceDB subject accepted %q without a valid account identity ID", value)
			}
		})
	}

	for _, tc := range []struct {
		name  string
		extra map[string]any
	}{
		{name: "missing session id", extra: map[string]any{}},
		{name: "malformed session id", extra: map[string]any{"id": "not-a-session-uuid"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			candidate := valid
			candidate.Extra = tc.extra
			if value, err := executeGatewayTemplate(t, headers["X-Session-Id"], candidate); err == nil {
				t.Fatalf("session header accepted %q without a valid session ID", value)
			}
		})
	}

	anonymous := gatewayTemplateSession{Subject: "anonymous"}
	value, err := executeGatewayTemplate(t, headers["X-Session-Id"], anonymous)
	if err != nil || value != "" {
		t.Fatalf("anonymous X-Session-Id = %q, error = %v; want empty", value, err)
	}
}

func TestEverySpiceDBAuthorizerUsesItsExactValidatedIdentityPayload(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}
	remoteCount := bytes.Count(rules, []byte("    handler: remote_json\n"))
	memberSubjectCount := bytes.Count(rules, []byte(memberSubjectTemplate))
	sessionIDCount := bytes.Count(rules, []byte(gatewaySessionIDTemplate))
	if remoteCount == 0 || memberSubjectCount+1 != remoteCount || sessionIDCount != memberSubjectCount {
		t.Fatalf("remote authorizers = %d, manage account identity subjects = %d, manage session IDs = %d; want one additional MCP admission authorizer", remoteCount, memberSubjectCount, sessionIDCount)
	}
	for _, required := range []string{
		`"account_identity_id": "`,
		`"session_id": "`,
		`"role": "ADMIN"`,
		`"role": "AUTHOR"`,
	} {
		if !bytes.Contains(rules, []byte(required)) {
			t.Fatalf("generated gateway authorizer is missing %q", required)
		}
	}
	for _, forbidden := range []string{`"namespace":`, `"object":`, `"relation":`, `"permission":`, `"subject_id":`, `/internal/authorization/gateway`} {
		if bytes.Contains(rules, []byte(forbidden)) {
			t.Fatalf("generated gateway authorizer retains obsolete field or endpoint %q", forbidden)
		}
	}
}

func TestGeneratedGatewayAuthorizerUsesTypedConnectEndpoint(t *testing.T) {
	root := mustRepoRoot(t)
	configuration, err := os.ReadFile(filepath.Join(root, "config/oathkeeper/oathkeeper.yml"))
	if err != nil {
		t.Fatalf("read Oathkeeper configuration: %v", err)
	}
	if !bytes.Contains(configuration, []byte("remote: __AUTHORIZATION_URL__/api.intra.v1.InternalGatewayAuthorizationService/AuthorizeGatewayAccess")) {
		t.Fatal("Oathkeeper configuration does not target the typed gateway authorization Connect endpoint")
	}
}

func TestRouteConfigRejectsUnsafeOrAmbiguousOrigins(t *testing.T) {
	base := repositoryRouteConfig(t)
	tests := []struct {
		name   string
		mutate func(*routeConfig)
		want   string
	}{
		{name: "http public origin", mutate: func(c *routeConfig) { c.Origins.API = "http://api.example.invalid" }, want: "must use HTTPS"},
		{name: "origin path", mutate: func(c *routeConfig) { c.Origins.Auth = "https://auth.example.invalid/login" }, want: "no path"},
		{name: "origin userinfo", mutate: func(c *routeConfig) { c.Origins.Collab = "https://user@collab.example.invalid" }, want: "no userinfo"},
		{name: "unsafe internal origin", mutate: func(c *routeConfig) { c.Origins.APIInternal = "ftp://oathkeeper.internal" }, want: "HTTP(S)"},
		{name: "unsafe upstream", mutate: func(c *routeConfig) { c.Upstreams.API = "ftp://backend.example.invalid" }, want: "HTTP(S)"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			candidate := base
			tt.mutate(&candidate)
			if err := candidate.validate(); err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("validate() error = %v, want containing %q", err, tt.want)
			}
		})
	}
}

func TestLoadRouteConfigReportsFileParseAndValidationFailures(t *testing.T) {
	missingRoot := t.TempDir()
	if err := Sync(missingRoot, true); err == nil || !strings.Contains(err.Error(), "read config/oathkeeper/routes.yml") {
		t.Fatalf("missing route config error = %v", err)
	}

	for _, tt := range []struct {
		name     string
		contents string
		want     string
	}{
		{name: "invalid yaml", contents: "origins: [\n", want: "parse config/oathkeeper/routes.yml"},
		{name: "invalid route", contents: "origins:\n  api: http://api.example.invalid\n", want: "validate config/oathkeeper/routes.yml"},
	} {
		t.Run(tt.name, func(t *testing.T) {
			root := t.TempDir()
			path := filepath.Join(root, routesFile)
			if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
				t.Fatalf("create route directory: %v", err)
			}
			if err := os.WriteFile(path, []byte(tt.contents), 0o644); err != nil {
				t.Fatalf("write route config: %v", err)
			}
			if _, err := loadRouteConfig(root); err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("loadRouteConfig() error = %v, want containing %q", err, tt.want)
			}
		})
	}
}

func TestGenerateRulesRejectsInvalidRouteConfig(t *testing.T) {
	routes := repositoryRouteConfig(t)
	routes.Origins.API = "%"
	if _, err := generateRules(routes); err == nil || !strings.Contains(err.Error(), "validate routes") {
		t.Fatalf("generateRules() error = %v", err)
	}
}

func TestGeneratedRulesMatchCheckedInFile(t *testing.T) {
	workingDirectory, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd() error = %v", err)
	}
	root, err := FindRepoRoot(workingDirectory)
	if err != nil {
		t.Fatalf("FindRepoRoot() error = %v", err)
	}
	current, err := os.ReadFile(filepath.Join(root, rulesFile))
	if err != nil {
		t.Fatalf("read checked-in rules: %v", err)
	}
	routes, err := loadRouteConfig(root)
	if err != nil {
		t.Fatalf("load route config: %v", err)
	}
	generated, err := generateRules(routes)
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}
	if !bytes.Equal(current, generated) {
		t.Fatalf("%s is stale; run `npm run generate:oathkeeper-rules`", rulesFile)
	}
}

func TestOgGenerationRulesUseExactAuthorizationRoles(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	roles, err := collectManageAuthorizationRoles()
	if err != nil {
		t.Fatalf("collectManageAuthorizationRoles() error = %v", err)
	}
	hasMethod := func(role policyv1.AuthorizationRole, method string) bool {
		for _, candidate := range roles[role]["AdminService"] {
			if candidate == method {
				return true
			}
		}
		return false
	}

	for _, method := range []string{"GetOgGenerationRun", "RegenerateAllOgImages"} {
		if !hasMethod(policyv1.AuthorizationRole_ADMIN, method) {
			t.Errorf("admin OG role is missing %s", method)
		}
	}
	for _, method := range []string{"GetLatestOgGeneration", "GetOgGeneration", "RegenerateOgImage"} {
		if hasMethod(policyv1.AuthorizationRole_ADMIN, method) {
			t.Errorf("authenticated OG method %s leaked into the admin role", method)
		}
	}

	for _, method := range []string{"GetLatestOgGeneration", "GetOgGeneration", "RegenerateOgImage"} {
		if !hasMethod(policyv1.AuthorizationRole_USER, method) {
			t.Errorf("authenticated OG role is missing %s", method)
		}
	}
	for _, method := range []string{"GetOgGenerationRun", "RegenerateAllOgImages"} {
		if hasMethod(policyv1.AuthorizationRole_USER, method) {
			t.Errorf("admin-only OG method %s leaked into the authenticated role", method)
		}
	}

	if bytes.Contains(rules, []byte("PublishOgRefresh")) {
		t.Fatal("generated Oathkeeper rules retain removed PublishOgRefresh RPC")
	}
}

func TestReleasedManageContractHardCutsAreReflected(t *testing.T) {
	roles, err := collectManageAuthorizationRoles()
	if err != nil {
		t.Fatalf("collectManageAuthorizationRoles() error = %v", err)
	}
	hasMethod := func(role policyv1.AuthorizationRole, service, method string) bool {
		for _, candidate := range roles[role][service] {
			if candidate == method {
				return true
			}
		}
		return false
	}

	for _, method := range []string{
		"InitializeDefaults",
		"DeleteUserPassword",
		"SetUserPassword",
		"RemoveUserPasswordEmail",
		"DeleteCurrentUserPassword",
		"RemoveCurrentUserPasswordEmail",
		"RequestRetranscodeAudio",
		"ReadAIDocument",
		"ValidateAIDocumentOperations",
	} {
		for _, role := range []policyv1.AuthorizationRole{
			policyv1.AuthorizationRole_USER,
			policyv1.AuthorizationRole_AUTHOR,
			policyv1.AuthorizationRole_ADMIN,
		} {
			for _, service := range []string{"EmailTemplateService", "MemberService", "AccountService", "FileService"} {
				if hasMethod(role, service, method) {
					t.Errorf("removed %s.%s remains in %s", service, method, role)
				}
			}
		}
	}

	for _, required := range []struct {
		role    policyv1.AuthorizationRole
		service string
		method  string
	}{
		{policyv1.AuthorizationRole_ADMIN, "AudienceService", "ArchiveSegment"},
		{policyv1.AuthorizationRole_ADMIN, "AudienceService", "RestoreSegment"},
		{policyv1.AuthorizationRole_ADMIN, "MemberService", "SetMemberTags"},
		{policyv1.AuthorizationRole_AUTHOR, "FileService", "GetFileDownloadPolicy"},
		{policyv1.AuthorizationRole_AUTHOR, "FileService", "UpdateFileDownloadPolicy"},
		{policyv1.AuthorizationRole_AUTHOR, "AudienceService", "ListSegmentsForAuthenticatedAccess"},
	} {
		if !hasMethod(required.role, required.service, required.method) {
			t.Errorf("released contract is missing %s.%s from %s", required.service, required.method, required.role)
		}
	}

	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}
	for _, removed := range []string{
		"InitializeDefaults",
		"DeleteUserPassword",
		"SetUserPassword",
		"RemoveUserPasswordEmail",
		"DeleteCurrentUserPassword",
		"RemoveCurrentUserPasswordEmail",
		"RequestRetranscodeAudio",
	} {
		if bytes.Contains(rules, []byte(removed)) {
			t.Errorf("generated rules retain removed RPC %s", removed)
		}
	}
}

func TestCurrentAIAndPersonalAccessTokenRoutesAreBrowserSessionOnly(t *testing.T) {
	roles, err := collectManageAuthorizationRoles()
	if err != nil {
		t.Fatalf("collectManageAuthorizationRoles() error = %v", err)
	}

	for service, want := range map[string]string{
		"AIDocumentService":            "ApplyAIDocumentOperations,OpenAIDocument",
		"AIEditorOrchestrationService": "CancelAIEditorTurn,ResolveAIEditorToolCall,StartAIEditorTurn",
	} {
		if got := strings.Join(roles[policyv1.AuthorizationRole_USER][service], ","); got != want {
			t.Errorf("authenticated %s methods = %q, want %q", service, got, want)
		}
		for _, role := range []policyv1.AuthorizationRole{
			policyv1.AuthorizationRole_AUTHOR,
			policyv1.AuthorizationRole_ADMIN,
		} {
			if methods := roles[role][service]; len(methods) != 0 {
				t.Errorf("%s unexpectedly has %s methods %v", role, service, methods)
			}
		}
	}

	var personalAccessTokenMethods []string
	for _, method := range roles[policyv1.AuthorizationRole_USER]["AccountService"] {
		if strings.Contains(method, "PersonalAccessToken") {
			personalAccessTokenMethods = append(personalAccessTokenMethods, method)
		}
	}
	wantPersonalAccessTokenMethods := "CreateMyPersonalAccessToken,DeleteMyPersonalAccessToken,ListMyPersonalAccessTokens,RegenerateMyPersonalAccessToken"
	if got := strings.Join(personalAccessTokenMethods, ","); got != wantPersonalAccessTokenMethods {
		t.Errorf("authenticated Account PAT methods = %q, want %q", got, wantPersonalAccessTokenMethods)
	}

	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}
	block := ruleBlock(t, rules, "manage-auth")
	for _, want := range [][]byte{
		[]byte("AIDocumentService/"),
		[]byte("AIEditorOrchestrationService/"),
		[]byte("AccountService/"),
		[]byte("      - POST\n"),
		[]byte("    - handler: cookie_session\n"),
		[]byte("    handler: allow\n"),
		[]byte("    - handler: header\n"),
		[]byte("    strip_path: /api/rpc\n"),
	} {
		if !bytes.Contains(block, want) {
			t.Errorf("authenticated browser rule is missing %q:\n%s", want, block)
		}
	}
	for _, forbidden := range [][]byte{
		[]byte("handler: bearer_token"),
		[]byte("handler: oauth2_introspection"),
		[]byte("handler: remote_json"),
	} {
		if bytes.Contains(block, forbidden) {
			t.Errorf("authenticated browser rule contains machine or duplicate authorization boundary %q:\n%s", forbidden, block)
		}
	}

	if bytes.Contains(rules, []byte("AIService/Chat")) || bytes.Contains(block, []byte("Chat")) {
		t.Fatal("generated rules retain the removed legacy AIService.Chat RPC")
	}
	mcp := ruleBlock(t, rules, "mcp")
	for _, browserService := range []string{"AIDocumentService", "AIEditorOrchestrationService", "AccountService"} {
		if bytes.Contains(mcp, []byte(browserService)) {
			t.Errorf("MCP gateway rule was widened with browser service %s:\n%s", browserService, mcp)
		}
	}
}

func TestRetiredManualSnapshotRPCsAreAbsentFromGatewayContract(t *testing.T) {
	roles, err := collectManageAuthorizationRoles()
	if err != nil {
		t.Fatalf("collectManageAuthorizationRoles() error = %v", err)
	}

	for _, retired := range []struct {
		service string
		method  string
	}{
		{service: "PageService", method: "CreatePageSnapshot"},
		{service: "PostService", method: "CreatePostSnapshot"},
		{service: "WorkService", method: "CreateWorkSnapshot"},
	} {
		for _, services := range roles {
			for _, method := range services[retired.service] {
				if method == retired.method {
					t.Errorf("released contract retains %s.%s", retired.service, retired.method)
				}
			}
		}
	}
	for _, retained := range []struct {
		role    policyv1.AuthorizationRole
		service string
		methods []string
	}{
		{role: policyv1.AuthorizationRole_ADMIN, service: "PageService", methods: []string{"ListPageVersions", "RestorePageVersion"}},
		{role: policyv1.AuthorizationRole_USER, service: "PostService", methods: []string{"ListPostVersions"}},
		{role: policyv1.AuthorizationRole_AUTHOR, service: "PostService", methods: []string{"RestorePostVersion"}},
		{role: policyv1.AuthorizationRole_ADMIN, service: "WorkService", methods: []string{"ListWorkVersions", "RestoreWorkVersion"}},
	} {
		for _, requiredMethod := range retained.methods {
			found := false
			for _, method := range roles[retained.role][retained.service] {
				if method == requiredMethod {
					found = true
					break
				}
			}
			if !found {
				t.Errorf("released contract is missing retained %s.%s from %s", retained.service, requiredMethod, retained.role)
			}
		}
	}

	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}
	for _, retired := range []string{"CreatePageSnapshot", "CreatePostSnapshot", "CreateWorkSnapshot"} {
		if bytes.Contains(rules, []byte(retired)) {
			t.Errorf("generated rules retain retired RPC %s", retired)
		}
	}
	for _, retained := range []string{
		"ListPageVersions", "RestorePageVersion",
		"ListPostVersions", "RestorePostVersion",
		"ListWorkVersions", "RestoreWorkVersion",
	} {
		if !bytes.Contains(rules, []byte(retained)) {
			t.Errorf("generated rules are missing retained RPC %s", retained)
		}
	}
}

func TestReleaseAndTrackManageRPCsAreAdminOnly(t *testing.T) {
	roles, err := collectManageAuthorizationRoles()
	if err != nil {
		t.Fatalf("collectManageAuthorizationRoles() error = %v", err)
	}

	services := map[string]protoreflect.ServiceDescriptor{
		"ReleaseService": managev1.File_api_manage_v1_release_proto.Services().ByName("ReleaseService"),
		"TrackService":   managev1.File_api_manage_v1_track_proto.Services().ByName("TrackService"),
	}
	for serviceName, descriptor := range services {
		if got := roles[policyv1.AuthorizationRole_USER][serviceName]; len(got) != 0 {
			t.Errorf("%s authenticated methods = %v, want none", serviceName, got)
		}
		if got := roles[policyv1.AuthorizationRole_AUTHOR][serviceName]; len(got) != 0 {
			t.Errorf("%s author methods = %v, want none", serviceName, got)
		}
		if got, want := len(roles[policyv1.AuthorizationRole_ADMIN][serviceName]), descriptor.Methods().Len(); got != want {
			t.Errorf("%s admin methods = %d, want all %d declared methods", serviceName, got, want)
		}
	}
}

func TestReleasedV127ContractHasNoLegacyAliases(t *testing.T) {
	translationJob := (&managev1.TranslationJob{}).ProtoReflect().Descriptor()
	if field := translationJob.Fields().ByName("retry_of_job_id"); field != nil {
		t.Errorf("released TranslationJob retains retry lineage alias %s", field.FullName())
	}

	formMeta := (&intrav1.FormMeta{}).ProtoReflect().Descriptor()
	if field := formMeta.Fields().ByName("webhooks"); field != nil {
		t.Errorf("released FormMeta retains removed webhook field %s", field.FullName())
	}
	if message := formMeta.ParentFile().Messages().ByName("FormWebhook"); message != nil {
		t.Errorf("released form contract retains removed message %s", message.FullName())
	}

	roles, err := collectManageAuthorizationRoles()
	if err != nil {
		t.Fatalf("collectManageAuthorizationRoles() error = %v", err)
	}
	hasListJobs := func(role policyv1.AuthorizationRole) bool {
		for _, method := range roles[role]["TranslationService"] {
			if method == "ListTranslationJobs" {
				return true
			}
		}
		return false
	}
	if !hasListJobs(policyv1.AuthorizationRole_USER) {
		t.Error("released ListTranslationJobs route is not authenticated")
	}
	if hasListJobs(policyv1.AuthorizationRole_ADMIN) {
		t.Error("released ListTranslationJobs route retains its retired admin alias")
	}
}

func TestNewsletterHardCutUsesOpenTokenUnsubscribeAndAdminMemberUnsubscribe(t *testing.T) {
	service := openv1.File_api_open_v1_newsletter_proto.Services().ByName("NewsletterService")
	if service == nil {
		t.Fatal("released api.open.v1.NewsletterService descriptor is missing")
	}
	if got := service.Methods().Len(); got != 1 {
		t.Fatalf("api.open.v1.NewsletterService method count = %d, want 1", got)
	}
	if method := service.Methods().ByName("Unsubscribe"); method == nil {
		t.Fatal("released api.open.v1.NewsletterService.Unsubscribe descriptor is missing")
	}
	request := (&openv1.UnsubscribeNewsletterRequest{}).ProtoReflect().Descriptor()
	if request.Fields().ByName("token") == nil {
		t.Fatal("public newsletter unsubscribe request is missing its signed token")
	}
	for _, retired := range []protoreflect.Name{"email", "user_id", "subscriber_id"} {
		if field := request.Fields().ByName(retired); field != nil {
			t.Errorf("public newsletter unsubscribe request retains identity field %s", field.FullName())
		}
	}

	roles, err := collectManageAuthorizationRoles()
	if err != nil {
		t.Fatalf("collectManageAuthorizationRoles() error = %v", err)
	}
	hasAdminUnsubscribe := false
	for _, method := range roles[policyv1.AuthorizationRole_ADMIN]["AccountService"] {
		if method == "UnsubscribeAccountFromNewsletter" {
			hasAdminUnsubscribe = true
			break
		}
	}
	if !hasAdminUnsubscribe {
		t.Fatal("admin AccountService route is missing UnsubscribeAccountFromNewsletter")
	}
	hasSelfMutation := false
	for _, method := range roles[policyv1.AuthorizationRole_USER]["AccountService"] {
		if method == "SetMyNewsletterSubscription" {
			hasSelfMutation = true
			break
		}
	}
	if !hasSelfMutation {
		t.Fatal("authenticated AccountService route is missing SetMyNewsletterSubscription")
	}

	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}
	openRule := ruleBlock(t, rules, "open-api")
	for _, want := range [][]byte{
		[]byte(`/api\.open\.v1\..*`),
		[]byte("      - POST\n"),
		[]byte("    - handler: anonymous\n"),
	} {
		if !bytes.Contains(openRule, want) {
			t.Errorf("open API rule does not cover the token unsubscribe boundary; missing %q", want)
		}
	}
	for _, retired := range [][]byte{
		[]byte("SubscriberService"),
		[]byte("/subscribe"),
		[]byte("/subscribe/confirm"),
	} {
		if bytes.Contains(rules, retired) {
			t.Errorf("generated rules retain retired newsletter route %q", retired)
		}
	}
}

func TestGenerateRulesHandlesCollectorResults(t *testing.T) {
	routes := repositoryRouteConfig(t)
	_, err := generateRulesWithCollector(routes, func() (map[policyv1.AuthorizationRole]serviceMethods, error) {
		return nil, errors.New("collector failed")
	})
	if err == nil || !strings.Contains(err.Error(), "collect manage access roles") {
		t.Fatalf("collector error = %v", err)
	}

	rules, err := generateRulesWithCollector(routes, func() (map[policyv1.AuthorizationRole]serviceMethods, error) {
		return map[policyv1.AuthorizationRole]serviceMethods{}, nil
	})
	if err != nil {
		t.Fatalf("empty collector error = %v", err)
	}
	if bytes.Contains(rules, []byte("# Manage API -")) {
		t.Fatal("empty collector generated manage API rules")
	}
}

func TestCollectManageAuthorizationRolesRejectsInvalidPolicies(t *testing.T) {
	tests := []struct {
		name   string
		policy *policyv1.AccessPolicy
		want   string
	}{
		{name: "missing", want: "missing access option"},
		{name: "unspecified", policy: &policyv1.AccessPolicy{}, want: "unspecified access role"},
		{name: "public", policy: &policyv1.AccessPolicy{Role: policyv1.AuthorizationRole_ANON}, want: "public access role is not allowed"},
		{name: "unsupported", policy: &policyv1.AccessPolicy{Role: policyv1.AuthorizationRole(99)}, want: "unsupported access role"},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			_, err := collectManageAuthorizationRolesFrom(manageRegistry(t, tt.policy))
			if err == nil || !strings.Contains(err.Error(), tt.want) {
				t.Fatalf("collect error = %v, want containing %q", err, tt.want)
			}
		})
	}
}

func TestCollectManageAuthorizationRolesSortsMethods(t *testing.T) {
	registry := manageRegistryWithMethods(t, &policyv1.AccessPolicy{
		Role: policyv1.AuthorizationRole_ADMIN,
	}, "Zulu", "Alpha")
	roles, err := collectManageAuthorizationRolesFrom(registry)
	if err != nil {
		t.Fatalf("collect error = %v", err)
	}
	methods := roles[policyv1.AuthorizationRole_ADMIN]["FixtureService"]
	if len(methods) != 2 || methods[0] != "Alpha" || methods[1] != "Zulu" {
		t.Fatalf("methods = %v", methods)
	}
}

func TestWriteRoleRuleRejectsUnsupportedRole(t *testing.T) {
	defer func() {
		if recovered := recover(); recovered == nil {
			t.Fatal("writeRoleRule did not panic for an unsupported role")
		}
	}()
	var out bytes.Buffer
	writeRoleRule(&out, repositoryRouteConfig(t), policyv1.AuthorizationRole(99), serviceMethods{"FixtureService": {"Read"}})
}

func TestRoleIDCoversEveryValue(t *testing.T) {
	tests := map[policyv1.AuthorizationRole]string{
		policyv1.AuthorizationRole_USER:   "auth",
		policyv1.AuthorizationRole_AUTHOR: "author",
		policyv1.AuthorizationRole_ADMIN:  "admin",
		policyv1.AuthorizationRole(99):    "unknown",
	}
	for role, want := range tests {
		if got := roleID(role); got != want {
			t.Fatalf("roleID(%v) = %q, want %q", role, got, want)
		}
	}
}

func TestCurrentManageAccessInventory(t *testing.T) {
	roles, err := collectManageAuthorizationRoles()
	if err != nil {
		t.Fatalf("collectManageAuthorizationRoles() error = %v", err)
	}

	counts := map[policyv1.AuthorizationRole]int{}
	for role, services := range roles {
		count := 0
		for _, methods := range services {
			count += len(methods)
		}
		counts[role] = count
	}
	if len(roles) != 3 {
		t.Errorf("generated roles = %d, want 3", len(roles))
	}
	for _, role := range []policyv1.AuthorizationRole{
		policyv1.AuthorizationRole_USER,
		policyv1.AuthorizationRole_AUTHOR,
		policyv1.AuthorizationRole_ADMIN,
	} {
		if counts[role] == 0 {
			t.Errorf("%s has no methods", role)
		}
	}
	total := counts[policyv1.AuthorizationRole_USER] +
		counts[policyv1.AuthorizationRole_AUTHOR] +
		counts[policyv1.AuthorizationRole_ADMIN]

	workingDirectory, err := os.Getwd()
	if err != nil {
		t.Fatalf("Getwd() error = %v", err)
	}
	root, err := FindRepoRoot(workingDirectory)
	if err != nil {
		t.Fatalf("FindRepoRoot() error = %v", err)
	}
	documentation, err := os.ReadFile(filepath.Join(root, "docs/oathkeeper-access-policy.md"))
	if err != nil {
		t.Fatalf("read Oathkeeper access policy: %v", err)
	}
	wantInventory := fmt.Sprintf(
		"<!-- manage-inventory: authenticated=%d author=%d admin=%d total=%d -->",
		counts[policyv1.AuthorizationRole_USER],
		counts[policyv1.AuthorizationRole_AUTHOR],
		counts[policyv1.AuthorizationRole_ADMIN],
		total,
	)
	if !bytes.Contains(documentation, []byte(wantInventory)) {
		t.Errorf("Oathkeeper access policy is missing current inventory %q", wantInventory)
	}
	for _, row := range []struct {
		label string
		count int
	}{
		{label: "Authenticated", count: counts[policyv1.AuthorizationRole_USER]},
		{label: "Author", count: counts[policyv1.AuthorizationRole_AUTHOR]},
		{label: "Admin", count: counts[policyv1.AuthorizationRole_ADMIN]},
	} {
		wantLabel := fmt.Sprintf("| %-13s |", row.label)
		wantCount := fmt.Sprintf("%d", row.count)
		if !bytes.Contains(documentation, []byte(wantLabel)) || !bytes.Contains(documentation, []byte(wantCount)) {
			t.Errorf("Oathkeeper access policy is missing current %s row/count %d", row.label, row.count)
		}
	}
}

func TestPostSeriesManagerRoutesDoNotRequireGlobalAuthor(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	authenticated := ruleBlock(t, rules, "manage-auth")
	wantAuthenticated := `SeriesService/(?:AssignPostToSeries|CheckSeriesSlugAvailable|DeleteSeriesFeaturedImage|GetSeriesWithManagers|ListMySeries|ListSeriesManagers|ListSeriesPosts|ReorderSeriesPosts|SetSeriesFeaturedImage|UnassignPostFromSeries|UpdateSeries)`
	if !bytes.Contains(authenticated, []byte(wantAuthenticated)) {
		t.Errorf("authenticated Series rule does not contain the exact Manager surface:\n%s", authenticated)
	}
	if bytes.Contains(authenticated, []byte("handler: remote_json")) {
		t.Errorf("authenticated Series rule still delegates to a global role:\n%s", authenticated)
	}

	admin := ruleBlock(t, rules, "manage-admin")
	wantAdmin := `SeriesService/(?:AddSeriesManager|CreateSeries|DeleteSeries|ListSeriesAdmin|ListSeriesSimple|RemoveSeriesManager)`
	if !bytes.Contains(admin, []byte(wantAdmin)) {
		t.Errorf("Admin-only Series rule does not contain the exact lifecycle and Manager-assignment surface:\n%s", admin)
	}
	if !bytes.Contains(admin, []byte("handler: remote_json")) {
		t.Errorf("Admin-only Series rule does not enforce the Admin role:\n%s", admin)
	}

	if bytes.Contains(ruleBlock(t, rules, "manage-author"), []byte("SeriesService/")) {
		t.Fatal("Post Series Manager routes still require the unrelated global Author role")
	}
}

func TestCurrentTranslationRoutesUseAnnotatedGatewayRoles(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	authenticated := ruleBlock(t, rules, "manage-auth")
	wantAuthenticated := `TranslationService/(?:CancelTranslationJob|ExportEntityTranslationXLIFF|GetEntityTranslation|ImportEntityTranslationXLIFF|ListEntityTranslations|ListTranslationJobs|ListTranslationLocales|RegenerateEntityTranslations|SetEntitySourceLocale)`
	if !bytes.Contains(authenticated, []byte(wantAuthenticated)) {
		t.Errorf("authenticated Translation rule does not contain the current resource-scoped surface:\n%s", authenticated)
	}

	admin := ruleBlock(t, rules, "manage-admin")
	wantAdmin := `TranslationService/(?:CreateTranslationProvider|DeleteTranslationProvider|GetTranslationOverview|GetTranslationSettings|ListTranslationProviders|UpdateTranslationProvider|UpdateTranslationSettings)`
	if !bytes.Contains(admin, []byte(wantAdmin)) {
		t.Errorf("admin Translation rule does not contain the current provider and settings surface:\n%s", admin)
	}
	for _, resourceMethod := range []string{"RegenerateEntityTranslations", "SetEntitySourceLocale"} {
		if bytes.Contains(admin, []byte(resourceMethod)) {
			t.Errorf("admin Translation rule retains resource-scoped method %s:\n%s", resourceMethod, admin)
		}
	}
}

func TestGeneratedRulesRestrictHTTPMethods(t *testing.T) {
	rules, err := generateRules(repositoryRouteConfig(t))
	if err != nil {
		t.Fatalf("generateRules() error = %v", err)
	}

	manageStart := bytes.Index(rules, []byte("# Manage API -"))
	mcpStart := bytes.Index(rules, []byte("# Remote MCP -"))
	if manageStart < 0 || mcpStart <= manageStart {
		t.Fatalf("manage or MCP section missing")
	}
	manageRules := rules[manageStart:mcpStart]
	for _, forbidden := range [][]byte{
		[]byte("      - GET\n"),
		[]byte("      - PUT\n"),
		[]byte("      - PATCH\n"),
		[]byte("      - DELETE\n"),
	} {
		if bytes.Contains(manageRules, forbidden) {
			t.Fatalf("manage rules contain non-POST method %q", forbidden)
		}
	}

	internalRule := ruleBlock(t, rules, "block-internal-api")
	for _, method := range []string{"GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"} {
		if !bytes.Contains(internalRule, []byte("      - "+method+"\n")) {
			t.Errorf("internal API deny rule is missing %s", method)
		}
	}
	openRule := ruleBlock(t, rules, "open-api")
	if !bytes.Contains(openRule, []byte("      - POST\n")) || bytes.Contains(openRule, []byte("      - GET\n")) {
		t.Errorf("open API rule must allow POST only:\n%s", openRule)
	}
}

func TestSyncWritesChecksAndReportsFailures(t *testing.T) {
	t.Setenv("AUTH_HEADER_NAME", "")
	t.Setenv("INTERNAL_SERVICE_HEADER_NAME", "")
	t.Setenv("SESSION_COOKIE_NAME", "")
	root := t.TempDir()
	rulesDirectory := filepath.Join(root, filepath.Dir(rulesFile))
	if err := os.MkdirAll(rulesDirectory, 0o755); err != nil {
		t.Fatalf("create rules directory: %v", err)
	}
	routeContents, err := os.ReadFile(filepath.Join(mustRepoRoot(t), routesFile))
	if err != nil {
		t.Fatalf("read route fixture: %v", err)
	}
	if err := os.WriteFile(filepath.Join(root, routesFile), routeContents, 0o644); err != nil {
		t.Fatalf("write route fixture: %v", err)
	}

	if err := Sync(root, false); err != nil {
		t.Fatalf("Sync(write) error = %v", err)
	}
	if err := Sync(root, true); err != nil {
		t.Fatalf("Sync(check) error = %v", err)
	}
	rulesPath := filepath.Join(root, rulesFile)
	if err := os.WriteFile(rulesPath, []byte("stale"), 0o644); err != nil {
		t.Fatalf("write stale rules: %v", err)
	}
	if err := Sync(root, true); err == nil || !strings.Contains(err.Error(), "is stale") {
		t.Fatalf("stale check error = %v", err)
	}
	if err := os.Remove(rulesPath); err != nil {
		t.Fatalf("remove rules: %v", err)
	}
	if err := Sync(root, true); err == nil || !strings.Contains(err.Error(), "read config/oathkeeper/rules.yml") {
		t.Fatalf("missing check error = %v", err)
	}
	if err := os.RemoveAll(rulesDirectory); err != nil {
		t.Fatalf("remove rules directory: %v", err)
	}
	if err := syncWithGenerator(root, false, func() ([]byte, error) { return []byte("rules"), nil }); err == nil || !strings.Contains(err.Error(), "write config/oathkeeper/rules.yml") {
		t.Fatalf("write error = %v", err)
	}

	generatorError := syncWithGenerator(root, false, func() ([]byte, error) {
		return nil, errors.New("generate failed")
	})
	if generatorError == nil || !strings.Contains(generatorError.Error(), "generate rules") {
		t.Fatalf("generator error = %v", generatorError)
	}
}

func TestFindRepoRootReportsMissingRepository(t *testing.T) {
	root := t.TempDir()
	_, err := FindRepoRoot(root)
	if err == nil || !strings.Contains(err.Error(), "repository root not found") {
		t.Fatalf("FindRepoRoot() error = %v", err)
	}
}

func manageRegistry(t *testing.T, policy *policyv1.AccessPolicy) *protoregistry.Files {
	t.Helper()
	return manageRegistryWithMethods(t, policy, "Execute")
}

func ruleBlock(t *testing.T, rules []byte, id string) []byte {
	t.Helper()
	start := bytes.Index(rules, []byte("- id: "+id+"\n"))
	if start < 0 {
		t.Fatalf("rule %s not found", id)
	}
	rest := rules[start:]
	if next := bytes.Index(rest[1:], []byte("\n- id: ")); next >= 0 {
		return rest[:next+1]
	}
	return rest
}

func ruleURLRegexp(t *testing.T, block []byte) *regexp.Regexp {
	t.Helper()
	match := regexp.MustCompile(`(?m)^    url: '<([^']+)>'$`).FindSubmatch(block)
	if len(match) != 2 {
		t.Fatalf("rule URL matcher missing:\n%s", block)
	}
	compiled, err := regexp.Compile("^(?:" + string(match[1]) + ")$")
	if err != nil {
		t.Fatalf("compile rule URL matcher %q: %v", match[1], err)
	}
	return compiled
}

func manageRegistryWithMethods(t *testing.T, policy *policyv1.AccessPolicy, methodNames ...string) *protoregistry.Files {
	t.Helper()
	methods := make([]*descriptorpb.MethodDescriptorProto, 0, len(methodNames))
	for _, methodName := range methodNames {
		options := &descriptorpb.MethodOptions{}
		if policy != nil {
			proto.SetExtension(options, policyv1.E_Access, policy)
		}
		methods = append(methods, &descriptorpb.MethodDescriptorProto{
			Name:       proto.String(methodName),
			InputType:  proto.String(".api.manage.v1.FixtureRequest"),
			OutputType: proto.String(".api.manage.v1.FixtureResponse"),
			Options:    options,
		})
	}
	file, err := protodesc.NewFile(&descriptorpb.FileDescriptorProto{
		Name:       proto.String("fixture/manage.proto"),
		Package:    proto.String("api.manage.v1"),
		Syntax:     proto.String("proto3"),
		Dependency: []string{policyv1.File_api_policy_v1_access_proto.Path()},
		MessageType: []*descriptorpb.DescriptorProto{
			{Name: proto.String("FixtureRequest")},
			{Name: proto.String("FixtureResponse")},
		},
		Service: []*descriptorpb.ServiceDescriptorProto{{
			Name:   proto.String("FixtureService"),
			Method: methods,
		}},
	}, protoregistry.GlobalFiles)
	if err != nil {
		t.Fatalf("build fixture descriptor: %v", err)
	}
	registry := new(protoregistry.Files)
	if err := registry.RegisterFile(file); err != nil {
		t.Fatalf("register fixture descriptor: %v", err)
	}
	return registry
}
