// Code generated by scripts/ci/generate-spicedb-schema.mjs.
// DO NOT EDIT.

export const spiceDbCatalogFingerprint = "b1c92baf58538b463ae2a94d9b26c3c7e920b22bf92ca71841196b017592a2fe" as const;

export const spiceDbResourceTypes = [
  "post",
  "artist",
  "label",
  "series",
  "page",
  "work",
  "release",
  "track",
  "program_event",
  "program_event_series",
  "file",
  "campaign",
  "audience_segment",
  "map_place",
  "site_setting",
  "menu",
  "category",
  "tag",
  "genre",
  "style",
  "format",
  "client",
  "member",
  "form",
  "email_template",
  "email_layout",
  "email_event_mapping",
  "mail_adapter",
  "email_suppression",
  "translation_settings",
  "translation_provider",
  "terms_history",
  "privacy_history",
  "map_theme"
] as const;

export type SpiceDbResourceType = (typeof spiceDbResourceTypes)[number];

export const spiceDbCapabilities = {
  "post": {
    "relations": [
      "policy",
      "author",
      "collaborator"
    ],
    "permissions": [
      "platform_admin",
      "platform_author",
      "author_manage",
      "collaborator_edit",
      "edit",
      "view",
      "view_archived",
      "edit_archived",
      "delete",
      "publish",
      "manage",
      "manage_participants",
      "manage_share_links"
    ]
  },
  "artist": {
    "relations": [
      "policy",
      "owner",
      "manager",
      "parent"
    ],
    "permissions": [
      "platform_admin",
      "owner_manage",
      "manager_manage",
      "edit",
      "view",
      "delete",
      "publish",
      "manage",
      "manage_participants",
      "manage_share_links"
    ]
  },
  "label": {
    "relations": [
      "policy",
      "owner",
      "manager",
      "parent"
    ],
    "permissions": [
      "platform_admin",
      "owner_manage",
      "manager_manage",
      "edit",
      "view",
      "delete",
      "publish",
      "manage",
      "manage_participants",
      "manage_share_links"
    ]
  },
  "series": {
    "relations": [
      "policy",
      "manager"
    ],
    "permissions": [
      "platform_admin",
      "manager_manage",
      "edit",
      "view",
      "delete",
      "publish",
      "manage",
      "manage_participants"
    ]
  },
  "page": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "publish",
      "manage",
      "manage_share_links"
    ]
  },
  "work": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "view_archived",
      "edit_archived",
      "delete",
      "publish",
      "manage",
      "manage_share_links"
    ]
  },
  "release": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "publish",
      "manage",
      "manage_share_links"
    ]
  },
  "track": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "program_event": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "view_archived",
      "edit_archived",
      "delete",
      "publish",
      "manage"
    ]
  },
  "program_event_series": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "publish",
      "manage"
    ]
  },
  "file": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "campaign": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "audience_segment": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "map_place": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "platform_author",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "site_setting": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "menu": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "category": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "tag": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "genre": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "style": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "format": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "client": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "member": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "form": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "publish",
      "manage",
      "manage_share_links"
    ]
  },
  "email_template": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "email_layout": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  },
  "email_event_mapping": {
    "relations": [],
    "permissions": []
  },
  "mail_adapter": {
    "relations": [],
    "permissions": []
  },
  "email_suppression": {
    "relations": [],
    "permissions": []
  },
  "translation_settings": {
    "relations": [],
    "permissions": []
  },
  "translation_provider": {
    "relations": [],
    "permissions": []
  },
  "terms_history": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "view_archived",
      "edit_archived",
      "delete",
      "publish",
      "manage",
      "manage_share_links"
    ]
  },
  "privacy_history": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "view_archived",
      "edit_archived",
      "delete",
      "publish",
      "manage",
      "manage_share_links"
    ]
  },
  "map_theme": {
    "relations": [
      "policy"
    ],
    "permissions": [
      "platform_admin",
      "view",
      "edit",
      "delete",
      "manage"
    ]
  }
} as const satisfies Record<
  SpiceDbResourceType,
  { readonly relations: readonly string[]; readonly permissions: readonly string[] }
>;

export type SpiceDbRelation = (typeof spiceDbCapabilities)[SpiceDbResourceType]["relations"][number];
export type SpiceDbPermission = (typeof spiceDbCapabilities)[SpiceDbResourceType]["permissions"][number];
